baseURL = "/"
languageCode = "en-us"
title = "Brainspace Technologies"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Service"
        url     = "/service"
        weight  = 3
    [[menu.nav]]
        name    = "Gallery"
        url     = "/gallery"
        weight  = 4
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 6

# Site Params
[params]
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"
    # Meta data
    description = "Airspace Hugo theme"
    author = "Themefisher"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Partner to Your Digital Journey"
        description = "Brainspace Technologies is a next generation technology,service and consulting company offering cutting edge IT solutions.We are uniquely positioned to provide what our customers need – complex software solutions to answer their requirements, delivered reliably on time, with excellent value for money."
        btn     = true
        btnText = "Intellegent Information Management"
        btnURL  = ""
        [[params.banner.flipText]]
            title   = "Content Services"
        [[params.banner.flipText]]
            title   = "Process Services"
        [[params.banner.flipText]]
            title   = "Analitycs Services"
        [[params.banner.flipText]]
            title   = "RPA Services" 
         [[params.banner.flipText]]
            title   = "Cloud Services"         

    # Homepage About Section
    [params.about]
        enable  = false
        title   = "ABOUT US"
        content = "Hello, I’m a UI/UX Designer & Front End Developer from Victoria, Australia. I hold a master degree of Web Design from the World University.And scrambled it to make a type specimen book. It has survived not only five centuries. <br> <br> Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, adipisci voluptatum repudiandae, natus impedit repellat aut officia illum at assumenda iusto reiciendis placeat. Temporibus, vero."
        image   = "images/about/about.jpg"

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT YOU THINK ?"
        content = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nobis,<br>possimus commodi, fugiat magnam temporibus vero magni recusandae? Dolore, maxime praesentium."
        btnText = "Contact Us"
        btnURL  = "/contact"

    # Portfolio Section On Homepage
    [params.portfolio]
        enable  = false
        title   = "Latest Works"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    # Feature Product Section
    [params.featureProduct]
        enable  = true
        title   = "SOME OF OUR FEATURES WORKS"
        subtitle= "Aliquam lobortis. Maecenas vestibulum mollis diam. Pellentesque auctor neque nec urna. Nulla sit amet est. Aenean posuere <br> tortor sed cursus feugiat, nunc augue blandit nunc, eu sollicitudin urna dolor sagittis lacus."

    
